services:
  graph:
    build:
      context: .
    ports:
      - "8001:8000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      # On dit au service graph d'utiliser la nouvelle variable pour son mot de passe
      - NEO4J_PASSWORD=${GRAPH_SERVICE_PASSWORD}
      - PORT=8000
  neo4j:
    image: neo4j:5.15
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:7474 || exit 1",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      # Ce service ne reçoit que la variable qu'il comprend
      - NEO4J_AUTH=${NEO4J_AUTH}

volumes:
  neo4j_data:
