# docker-compose.yml - Version finale et sécurisée

services:
  graph:
    build:
      context: .
    expose:
      - "8000"
    labels:
      - "coolify.port=8000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${GRAPH_SERVICE_USER}
      - NEO4J_PASSWORD=${GRAPH_SERVICE_PASSWORD}
      - PORT=8000
      # Cette variable est nécessaire pour la sécurité de l'API que nous avons ajoutée au code.
      - GRAPHITI_API_KEY=${GRAPHITI_API_KEY}

  neo4j:
    image: neo4j:5.26.2
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    # --- MODIFICATION DE SÉCURITÉ ---
    # La section 'ports' est désactivée pour cacher la base de données d'Internet.
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"
    # On lie le port 7474 du conteneur au port 7474
      # de l'interface localhost (127.0.0.1) du serveur.
      # Il ne sera pas accessible depuis l'extérieur.
      - "127.0.0.1:7474:7474"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

volumes:
  neo4j_data:
