# docker-compose.yml - Version la plus simple et logique

services:
  graph:
    build:
      context: .
    expose:
      - "8000"

    # --- SÉCURITÉ AVEC LES VARIABLES DU SERVICE ---
    labels:
      - "coolify.port=8000"
      - "coolify.caddy.1=basicauth {"
      # Cette syntaxe {env.NOM_VARIABLE} demande à Coolify de lire
      # les variables d'environnement de CE service lors du déploiement.
      - "coolify.caddy.2=  {env.BASIC_AUTH_USER} {env.BASIC_AUTH_PASS}"
      - "coolify.caddy.3=}"
      # --- FIN DE LA SECTION SÉCURITÉ ---

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      # Ces variables sont pour votre application, pas pour le proxy.
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${GRAPH_SERVICE_USER}
      - NEO4J_PASSWORD=${GRAPH_SERVICE_PASSWORD}
      - PORT=8000

  neo4j:
    image: neo4j:5.26.2
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:7474 || exit 1",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

volumes:
  neo4j_data:
