# docker-compose.yml - Version finale avec image Caddy personnalisée

services:
  caddy:
    # --- MODIFICATION CLÉ ICI ---
    # Au lieu de 'image: caddy:latest', on dit à Docker de construire
    # une image en utilisant le Dockerfile qui se trouve dans le dossier ./caddy_config
    build:
      context: ./caddy_config
    restart: unless-stopped
    depends_on:
      - graph
    expose:
      - "80"
    # On n'a plus besoin de la section 'volumes', car le fichier est déjà dans l'image.
    environment:
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
    labels:
      - "coolify.port=80"

  graph:
    build:
      context: .
    expose:
      - "8000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${GRAPH_SERVICE_USER}
      - NEO4J_PASSWORD=${GRAPH_SERVICE_PASSWORD}
      - PORT=8000

  neo4j:
    image: neo4j:5.26.2
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}

volumes:
  neo4j_data:
